### ISSUE TITLE
[Compat]: Inventory lots with the same price but different dates

### ISSUE THREAD

**Issue by aaronj1335** [rustledger/rustledger#273]
### Description

Seems like maybe a key for an inventory is based on amount but not date?

The interesting thing is if I change 2018-12-06 to 2025-01-01, I don't get any difference in output.

### Beancount File

```text
2025-01-01 open Assets:Abc ABC
2025-01-01 open Assets:Cash
2025-01-01 open Equity:Opening

2026-01-04 balance Assets:Abc      0 ABC

2026-01-03 * "Sell"
  Assets:Abc                      -2 ABC {10.01 USD, 2018-12-06}
  Assets:Abc                      -1 ABC {10.01 USD}
  Assets:Cash                  30.03 USD

2026-01-01 * "..."
  Assets:Abc                       2 ABC {10.01 USD, 2018-12-06}
  Assets:Abc                       1 ABC {10.01 USD}
  Equity:Opening
```

### Python Beancount Output

```text
# Exit 0 no output
```

### Rustledger Output

```text
/path/to/test.beancount:7: error[E4001]: No matching lot for ABC in Assets:Abc (2026-01-03)
  context: cost spec: Some(CostSpec { number_per: Some(10.01), number_total: None, currency: Some(InternedStr("USD")), date: Some(2025-01-01), label: None, merge: false })

/path/to/test.beancount:5: error[E2001]: Balance assertion failed for Assets:Abc: expected 0 ABC, got 1 ABC (2026-01-04)
  context: difference: 1, tolerance: 0

✗ 2 errors
```

### Python Beancount Version

3.2.0

### Rustledger Version

0.8.1

**Comment by robcohen** [comment]
Verified this works correctly - added regression test in PR #285. The lot matching correctly distinguishes lots with the same price but different dates.
